<?php

namespace Tests\Browser;

use Laravel\Dusk\Browser;
use Tests\DuskTestCase;

class livedb2 extends DuskTestCase
{
    /**
     * A Dusk test testReport.
     *
     * @return void
     *
     * @author Priya
     */
    protected $browser;

    public function testExample()
    {
        $this->browse(function (Browser $browser) {
            $this->browser = $browser;
            $this->Login();
            $this->Merchants();
            $this->assign();
            $this->payment();
        });
    }

    public function Login()
    {
        $this->browser
                    ->visit('/login')
                    ->type('email', 'admin@investor.portal')
                    ->type('password', 'admin987987')
                    ->press('Login')
                    ->visit('/admin/dashboard')
                    ->assertPathIs('/admin/dashboard');
    }

    public function Merchants()
    {
        $this->browser->visit('/admin/merchants/create')
             ->type('name', 'iocod1')
             ->type('first_name', 'iocod1')
             ->type('last_name', 'test1')
                ->select('state_id', '3')
                  ->select('industry_id', '32')
             // ->type('email','iocod481@yahoo.in')
             // ->check('email_notification')
             ->type('merchant_email', 'test1@gmail.com')
                ->pause('1000')
             ->type('date_funded1', '03-05-2020')
                ->pause('6000')
             ->type('funded', '25000')
             ->pause('6000')
             ->type('max_participant_fund_per', '100')
             ->pause('3000')
             ->type('company_per[3]', '50')
             ->pause('3000')
             ->type('company_per[4]', '50')
             ->pause('3000')
             ->type('factor_rate', '1.3')
             ->type('commission', '10')
             ->type('pmnts', '10')
               ->pause('1000')
            ->type('credit_score', '500')
             ->select('sub_status_flag', '1')

             ->select('sub_status_id', '1')
             ->select('advance_type', 'Daily ACH')
             ->select('marketplace_status', '0')
             ->select('source_id', '1')

             ->select('lender_id', '20')
             ->radio('m_s_prepaid_status', '2')
             ->select('underwriting_fee', '1.75')
             ->check('underwriting_status[]', '1')
             ->check('underwriting_status[]', '2')
             ->pause('2000')
            ->check('ach_pull')
             ->pause('6000')
            ->type('account_holder_name', 'federal')
                ->pause('3000')
            ->type('routing_number', '082000549')
             ->pause('6000')
            ->type('account_number', '0001234005678')
            ->clickLink('Confirm')
           ->pause('6000')
             // ->check('email_notification')
             ->press('Create')
             ->pause('6000')
             ->press('×');

        $this->browser->visit('/admin/merchants/create')
             ->type('name', 'iocod2')
             ->type('first_name', 'iocod2')
             ->type('last_name', 'test2')
                  ->select('state_id', '5')
                  ->select('industry_id', '1')
             // ->type('email','iocod481@yahoo.in')
             // ->check('email_notification')
             ->type('merchant_email', 'test22@gmail.com')
             ->pause('1000')
             ->type('date_funded1', '04-01-2021')
             ->pause('6000')
             ->type('funded', '10050')
             ->pause('6000')
             ->type('max_participant_fund_per', '100')
             ->pause('6000')
             ->type('company_per[3]', '20.5')
             ->pause('3000')
             ->type('company_per[4]', '20.5')
             ->pause('3000')
             ->type('company_per[5]', '59')
             ->pause('3000')
             ->type('factor_rate', '1.5')
             ->type('commission', '8.5')
             ->type('pmnts', '10')
            ->pause('1000')
            ->type('credit_score', '580')
             ->select('sub_status_flag', '1')

             ->select('sub_status_id', '1')
             ->select('advance_type', 'Weekly ACH')
             ->select('marketplace_status', '0')
             ->select('source_id', '1')

             ->select('lender_id', '21')
             // ->radio('m_s_prepaid_status', '2')
             // ->select('underwriting_fee', '1.75')
             // ->check('underwriting_status[]', '1')
             // ->check('underwriting_status[]', '2')
             ->pause('2000')
             // ->check('email_notification')
            ->check('ach_pull')
            ->pause('5000')
            ->type('account_holder_name', 'federal')
          ->pause('2000')
            ->type('routing_number', '121122676')
             ->pause('3000')
            ->type('account_number', '002569786122')
            ->pause('1000')
            ->clickLink('Confirm')
            ->pause('4000')
             ->press('Create')
             ->pause('6000')
             ->press('×');

        $this->browser->visit('/admin/merchants/create')
             ->type('name', 'iocod3')
             ->type('first_name', 'merch3')
             ->type('last_name', 'test3')
             ->pause('1000')
               ->select('state_id', '4')
                 ->select('industry_id', '2')
             // ->type('email','iocod481@yahoo.in')
             // ->check('email_notification')
             ->type('merchant_email', 'test3@gmail.com')
                ->pause('1000')
             ->type('date_funded1', '03-30-2021')
                ->pause('6000')
             ->type('funded', '25000')
              ->pause('6000')
             ->type('max_participant_fund_per', '100')
              ->pause('3000')
             ->type('company_per[3]', '33.33')
             ->pause('3000')
             ->type('company_per[4]', '66.67')
             ->pause('3000')
             ->type('factor_rate', '1.77')
             ->type('commission', '15')
             ->type('pmnts', '15')
             ->pause('1000')
             ->type('credit_score', '520')
             ->select('sub_status_flag', '1')

             ->select('sub_status_id', '1')
             ->select('advance_type', 'Daily ACH')
             ->select('marketplace_status', '0')
             ->select('source_id', '2')

             ->select('lender_id', '22')
             // ->radio('m_s_prepaid_status', '2')
             // ->select('underwriting_fee', '1.75')
             // ->check('underwriting_status[]', '1')
             // ->check('underwriting_status[]', '2')
             ->pause('2000')
             // ->check('email_notification')
          ->check('ach_pull')
                ->pause('6000')
            ->type('account_holder_name', 'federal')
             ->pause('2000')
            ->type('routing_number', '122235821')
             ->pause('3000')
            ->type('account_number', '234500001234')
            ->clickLink('Confirm')
            ->pause('4000')
             ->press('Create')
             ->pause('6000')
             ->press('×');

        $this->browser->visit('/admin/merchants/create')
             ->type('name', 'iocod4')
             ->type('first_name', 'merch4')
             ->type('last_name', 'test4')
                ->select('state_id', '1')
                  ->select('industry_id', '3')
             // ->type('email','iocod481@yahoo.in')
             // ->check('email_notification')
             ->type('merchant_email', 'test4@gmail.com')
                ->pause('1000')
             ->type('date_funded1', '05-05-2020')
                ->pause('6000')
             ->type('funded', '55000')
             ->pause('6000')
             ->type('max_participant_fund_per', '25')
             ->pause('3000')
             ->type('company_per[3]', '18.56')
             ->pause('3000')
             // ->type('company_per[4]', '50')
             // ->pause('6000')
             ->type('factor_rate', '1.9')
             ->type('commission', '20')
             ->type('pmnts', '20')
            ->pause('1000')
             ->type('credit_score', '500')
             ->select('sub_status_flag', '1')

             ->select('sub_status_id', '1')
             ->select('advance_type', 'Weekly ACH')
             ->select('marketplace_status', '0')
             ->select('source_id', '1')

             ->select('lender_id', '23')
             // ->radio('m_s_prepaid_status', '2')
             // ->select('underwriting_fee', '1.75')
             // ->check('underwriting_status[]', '1')
             // ->check('underwriting_status[]', '2')
             ->pause('2000')
             // ->check('email_notification')
     ->check('ach_pull')
                ->pause('6000')
            ->type('account_holder_name', 'federal')
             ->pause('2000')
            ->type('routing_number', '082000549')
             ->pause('3000')
            ->type('account_number', '000123000045678')
            ->clickLink('Confirm')
            ->pause('4000')
             ->press('Create')
             ->pause('6000')
             ->press('×');

        $this->browser->visit('/admin/merchants/create')
             ->type('name', 'iocod5')
             ->type('first_name', 'merch5')
             ->type('last_name', 'test5')
               ->select('state_id', '2')
                  ->select('industry_id', '4')
             // ->type('email','iocod481@yahoo.in')
             // ->check('email_notification')
             ->type('merchant_email', 'test5@gmail.com')
                ->pause('1000')
             ->type('date_funded1', '03-01-2021')
                ->pause('6000')
             ->type('funded', '80500')
             ->pause('3000')
             ->type('max_participant_fund_per', '50')
             ->pause('3000')
             ->type('company_per[3]', '50')
             ->pause('3000')
             ->type('company_per[4]', '50')
             ->pause('3000')
             ->type('factor_rate', '1.88')
             ->type('commission', '14')
             ->type('pmnts', '20')
            ->pause('1000')
             ->type('credit_score', '500')
             ->select('sub_status_flag', '1')

             ->select('sub_status_id', '1')
             ->select('advance_type', 'Daily ACH')
             ->select('marketplace_status', '0')
             ->select('source_id', '1')

             ->select('lender_id', '20')
             // ->radio('m_s_prepaid_status', '2')
             // ->select('underwriting_fee', '1.75')
             // ->check('underwriting_status[]', '1')
             // ->check('underwriting_status[]', '2')
             ->pause('2000')
             // ->check('email_notification')
            ->check('ach_pull')
                ->pause('6000')
            ->type('account_holder_name', 'federal')
             ->pause('2000')
            ->type('routing_number', '122235821')
             ->pause('3000')
            ->type('account_number', '000004547678758')
            ->clickLink('Confirm')
            ->pause('4000')
             ->press('Create')
             ->pause('6000')
             ->press('×');

        $this->browser->visit('/admin/merchants/create')
             ->type('name', 'iocod6')
             ->type('first_name', 'merch6')
             ->type('last_name', 'test6')
                ->select('state_id', '6')
                   ->select('industry_id', '5')
             // ->type('email','iocod481@yahoo.in')
             // ->check('email_notification')
             ->type('merchant_email', 'test6@gmail.com')
                ->pause('1000')
             ->type('date_funded1', '01-05-2021')
                ->pause('6000')
             ->type('funded', '10000')
             ->pause('3000')
             ->type('max_participant_fund_per', '80')
             ->pause('3000')
             ->type('company_per[3]', '50')
             ->pause('6000')
             // ->type('company_per[4]', '50')
             // ->pause('6000')
             ->type('factor_rate', '1.66')
             ->type('commission', '15')
             ->type('pmnts', '25')
               ->pause('1000')
                  ->type('credit_score', '500')
             ->select('sub_status_flag', '1')

             ->select('sub_status_id', '1')
             ->select('advance_type', 'Weekly ACH')
             ->select('marketplace_status', '0')
             ->select('source_id', '1')

             ->select('lender_id', '24')
             // ->radio('m_s_prepaid_status', '2')
             // ->select('underwriting_fee', '1.75')
             // ->check('underwriting_status[]', '1')
             // ->check('underwriting_status[]', '2')
             ->pause('2000')
             // ->check('email_notification')
           ->check('ach_pull')
                ->pause('6000')
            ->type('account_holder_name', 'federal')
             ->pause('2000')
            ->type('routing_number', '082000549')
             ->pause('3000')
            ->type('account_number', '000123451111678')
            ->clickLink('Confirm')
            ->pause('4000')
             ->press('Create')
             ->pause('6000')
             ->press('×');

        $this->browser->visit('/admin/merchants/create')
             ->type('name', 'iocod7')
             ->type('first_name', 'merch7')
             ->type('last_name', 'test7')
                ->select('state_id', '7')
                    ->select('industry_id', '6')
             // ->type('email','iocod481@yahoo.in')
             // ->check('email_notification')
             ->type('merchant_email', 'test7@gmail.com')
                ->pause('1000')
             ->type('date_funded1', '02-25-2021')
                ->pause('6000')
             ->type('funded', '20000')
              ->pause('3000')
             ->type('max_participant_fund_per', '100')
             ->pause('6000')
             ->type('company_per[3]', '25')
             ->pause('3000')
             ->type('company_per[4]', '75')
             ->pause('3000')
             ->type('factor_rate', '1.56')
             ->type('commission', '14')
             ->type('pmnts', '36')
               ->pause('1000')
                  ->type('credit_score', '500')
             ->select('sub_status_flag', '1')

             ->select('sub_status_id', '1')
             ->select('advance_type', 'Daily ACH')
             ->select('marketplace_status', '0')
             ->select('source_id', '1')

             ->select('lender_id', '23')
             // ->radio('m_s_prepaid_status', '2')
             // ->select('underwriting_fee', '1.75')
             // ->check('underwriting_status[]', '1')
             // ->check('underwriting_status[]', '2')
             ->pause('2000')
             // ->check('email_notification')
            ->check('ach_pull')
                ->pause('6000')
            ->type('account_holder_name', 'federal')
             ->pause('2000')
            ->type('routing_number', '122235821')
             ->pause('3000')
            ->type('account_number', '334455667710')
            ->clickLink('Confirm')
            ->pause('4000')
             ->press('Create')
             ->pause('6000')
             ->press('×');

        $this->browser->visit('/admin/merchants/create')
             ->type('name', 'iocod8')
             ->type('first_name', 'merch8')
             ->type('last_name', 'test8')
         ->select('state_id', '8')
            ->select('industry_id', '7')
             // ->type('email','iocod481@yahoo.in')
             // ->check('email_notification')

             ->type('merchant_email', 'test8@gmail.com')
                ->pause('1000')
             ->type('date_funded1', '03-03-2021')
                ->pause('6000')
             ->type('funded', '15240')

              ->pause('6000')
             ->type('max_participant_fund_per', '100')
             ->pause('1000')
             ->type('company_per[3]', '20')
             ->pause('6000')
             ->type('company_per[4]', '50')
             ->pause('6000')
             ->type('factor_rate', '1.7')
             ->type('commission', '18')
             ->type('pmnts', '20')
               ->pause('1000')
                  ->type('credit_score', '500')
             ->select('sub_status_flag', '1')

             ->select('sub_status_id', '1')
             ->select('advance_type', 'Weekly ACH')
             ->select('marketplace_status', '0')
             ->select('source_id', '1')

             ->select('lender_id', '24')
             // ->radio('m_s_prepaid_status', '2')
             // ->select('underwriting_fee', '1.75')
             // ->check('underwriting_status[]', '1')
             // ->check('underwriting_status[]', '2')
             ->pause('2000')
             // ->check('email_notification')
  ->check('ach_pull')
                ->pause('6000')
            ->type('account_holder_name', 'federal')
             ->pause('2000')
            ->type('routing_number', '122235821')
             ->pause('3000')
            ->type('account_number', '7770000033444')
            ->clickLink('Confirm')
            ->pause('4000')
             ->press('Create')
             ->pause('6000')
             ->press('×');

        $this->browser->visit('/admin/merchants/create')
             ->type('name', 'iocod9')
             ->type('first_name', 'merch9')
             ->type('last_name', 'test9')
            ->select('state_id', '12')
                 ->select('industry_id', '8')
             // ->type('email','iocod481@yahoo.in')
             // ->check('email_notification')

             ->type('merchant_email', 'test9@gmail.com')
                ->pause('1000')
             ->type('date_funded1', '02-05-2021')
                ->pause('6000')
             ->type('funded', '54253')
             ->pause('6000')
             ->type('max_participant_fund_per', '100')
             ->pause('6000')
             ->type('company_per[3]', '50')
             ->pause('3000')
             ->type('company_per[4]', '50')
             ->pause('3000')
             ->type('factor_rate', '1.9')
             ->type('commission', '5')
             ->type('pmnts', '10')
               ->pause('1000')
                  ->type('credit_score', '500')
             ->select('sub_status_flag', '1')

             ->select('sub_status_id', '1')
             ->select('advance_type', 'Daily ACH')
             ->select('marketplace_status', '0')
             ->select('source_id', '1')

             ->select('lender_id', '23')
             // ->radio('m_s_prepaid_status', '2')
             // ->select('underwriting_fee', '1.75')
             // ->check('underwriting_status[]', '1')
             // ->check('underwriting_status[]', '2')
             ->pause('2000')
             // ->check('email_notification')
  ->check('ach_pull')
                ->pause('6000')
            ->type('account_holder_name', 'federal')
             ->pause('2000')
            ->type('routing_number', '082000549')
             ->pause('3000')
            ->type('account_number', '00012345678')
            ->clickLink('Confirm')
            ->pause('4000')
             ->press('Create')
             ->pause('6000')
             ->press('×');

        $this->browser->visit('/admin/merchants/create')
             ->type('name', 'iocod10')
             ->type('first_name', 'merch10')
             ->type('last_name', 'test10')
     ->select('state_id', '11')
             ->select('industry_id', '8')
             // ->type('email','iocod481@yahoo.in')
             // ->check('email_notification')
             ->type('merchant_email', 'test10@gmail.com')
                ->pause('1000')
             ->type('date_funded1', '03-14-2021')
                ->pause('6000')
             ->type('funded', '25000')
             ->pause('3000')
             ->type('max_participant_fund_per', '75')
             ->pause('3000')
             ->type('company_per[3]', '30')
             ->pause('3000')
             // ->type('company_per[4]', '50')
             // ->pause('6000')
             ->type('factor_rate', '2')
             ->type('commission', '8')
             ->type('pmnts', '30')
               ->pause('1000')
                  ->type('credit_score', '500')
             ->select('sub_status_flag', '1')

             ->select('sub_status_id', '1')
             ->select('advance_type', 'Weekly ACH')
             ->select('marketplace_status', '0')
             ->select('source_id', '1')

             ->select('lender_id', '22')
             // ->radio('m_s_prepaid_status', '2')
             // ->select('underwriting_fee', '1.75')
             // ->check('underwriting_status[]', '1')
             // ->check('underwriting_status[]', '2')
             ->pause('2000')
             // ->check('email_notification')
  ->check('ach_pull')
                ->pause('6000')
            ->type('account_holder_name', 'federal')
             ->pause('2000')
            ->type('routing_number', '121122676')
             ->pause('3000')
            ->type('account_number', '00012345678')
            ->clickLink('Confirm')
            ->pause('4000')
             ->press('Create')
             ->pause('6000')
             ->press('×');

        $this->browser->visit('/admin/merchants/create')
             ->type('name', 'iocod11')
             ->type('first_name', 'merch11')
             ->type('last_name', 'test11')
           ->select('state_id', '8')
            ->select('industry_id', '8')
             // ->type('email','iocod481@yahoo.in')
             // ->check('email_notification')

             ->type('merchant_email', 'test11@gmail.com')
                ->pause('1000')
             ->type('date_funded1', '12-12-2020')
                ->pause('3000')
             ->type('funded', '40000')
              ->pause('3000')
             ->type('max_participant_fund_per', '50')
             ->pause('3000')
             ->type('company_per[3]', '50')
             ->pause('3000')
             // ->type('company_per[4]', '50')
             // ->pause('6000')
             ->type('factor_rate', '1.25')
             ->type('commission', '13')
             ->type('pmnts', '20')
               ->pause('1000')
                  ->type('credit_score', '500')
             ->select('sub_status_flag', '1')

             ->select('sub_status_id', '1')
             ->select('advance_type', 'Daily ACH')
             ->pause('2000')
             ->select('marketplace_status', '1')
            ->pause('2000')
            ->check('notify_investors')
             ->select('source_id', '1')

             ->select('lender_id', '21')
             // ->radio('m_s_prepaid_status', '2')
             // ->select('underwriting_fee', '1.75')
             // ->check('underwriting_status[]', '1')
             // ->check('underwriting_status[]', '2')
             ->pause('2000')
             // ->check('email_notification')
    ->check('ach_pull')
                ->pause('6000')
            ->type('account_holder_name', 'federal')
             ->pause('2000')
            ->type('routing_number', '082000549')
             ->pause('3000')
            ->type('account_number', '00012345678')
            ->clickLink('Confirm')
            ->pause('4000')
             ->press('Create')
             ->pause('6000')
             ->press('×');

        $this->browser->visit('/admin/merchants/create')
             ->type('name', 'iocod12')
             ->type('first_name', 'merch12')
             ->type('last_name', 'test12')
            ->select('state_id', '9')
            ->select('industry_id', '8')
             // ->type('email','iocod481@yahoo.in')
             // ->check('email_notification')
             ->type('merchant_email', 'test12@gmail.com')
                ->pause('1000')
             ->type('date_funded1', '03-05-2022')
                ->pause('3000')
             ->type('funded', '150000')
             ->pause('3000')
             ->type('max_participant_fund_per', '100')
             ->pause('3000')
             ->type('company_per[3]', '25')
             ->pause('3000')
             // ->type('company_per[4]', '50')
             // ->pause('6000')
             ->type('factor_rate', '1.4')
             ->type('commission', '14')
             ->type('pmnts', '80')
               ->pause('1000')
                  ->type('credit_score', '500')
             ->select('sub_status_flag', '1')

             ->select('sub_status_id', '1')
             ->select('advance_type', 'Weekly ACH')
             ->select('marketplace_status', '1')
             ->pause('2000')
              ->check('notify_investors')
             ->select('source_id', '1')

             ->select('lender_id', '23')
             // ->radio('m_s_prepaid_status', '2')
             // ->select('underwriting_fee', '1.75')
             // ->check('underwriting_status[]', '1')
             // ->check('underwriting_status[]', '2')
             ->pause('2000')
             // ->check('email_notification')
 ->check('ach_pull')
                ->pause('6000')
            ->type('account_holder_name', 'federal')
             ->pause('2000')
            ->type('routing_number', '121122676')
             ->pause('3000')
            ->type('account_number', '00012345678')
            ->clickLink('Confirm')
            ->pause('4000')
             ->press('Create')
             ->pause('6000')
             ->press('×');

        $this->browser->visit('/admin/merchants/create')
             ->type('name', 'iocod13')
             ->type('first_name', 'merch13')
             ->type('last_name', 'test13')
        ->select('state_id', '10')
             ->select('industry_id', '8')
             // ->type('email','iocod481@yahoo.in')
             // ->check('email_notification')
             ->type('merchant_email', 'test13@gmail.com')
                ->pause('3000')
             ->type('date_funded1', '05-20-2021')
                ->pause('3000')
             ->type('funded', '25000')
             ->pause('6000')
           ->type('max_participant_fund_per', '100')
            ->pause('6000')
             ->pause('6000')
             // ->type('company_per[3]', '50')
             // ->pause('6000')
             ->type('company_per[4]', '20')
             ->pause('6000')
             ->type('company_per[5]', '80')
             ->type('factor_rate', '1.5')
              ->pause('6000')
             ->type('commission', '18')
             ->type('pmnts', '25')
            ->pause('1000')
            ->type('credit_score', '500')
             ->select('sub_status_flag', '1')

             ->select('sub_status_id', '1')
             ->select('advance_type', 'Daily ACH')
             ->select('marketplace_status', '0')
             ->select('source_id', '1')

             ->select('lender_id', '24')
               ->select('label', '5')
             // ->radio('m_s_prepaid_status', '2')
             // ->select('underwriting_fee', '1.75')
             // ->check('underwriting_status[]', '1')
             // ->check('underwriting_status[]', '2')
             ->pause('2000')
             // ->check('email_notification')
       ->check('ach_pull')
                ->pause('6000')
            ->type('account_holder_name', 'federal')
            ->pause('2000')
            ->type('routing_number', '082000549')
             ->pause('3000')
            ->type('account_number', '00055512345678')
            ->clickLink('Confirm')
            ->pause('4000')
             ->press('Create')
             ->pause('6000')
             ->press('×');

        $this->browser->visit('/admin/merchants/create')
             ->type('name', 'iocod14')
             ->type('first_name', 'merch14')
             ->type('last_name', 'test14')
             ->select('state_id', '9')
                ->select('industry_id', '8')
             // ->type('email','iocod481@yahoo.in')
             // ->check('email_notification')

             ->type('merchant_email', 'test14@gmail.com')
                ->pause('1000')
             ->type('date_funded1', '05-05-2020')
                ->pause('6000')
             ->type('funded', '0')
             ->pause('6000')
             //  ->pause('6000')
             // ->type('max_participant_fund_per', '100')
             // ->pause('6000')
             //  ->pause('6000')
             // ->type('company_per[3]', '50')
             // ->pause('6000')
             // ->type('company_per[4]', '50')
             // ->pause('6000')
             ->type('factor_rate', '1.8')
             ->type('commission', '12')
             ->type('pmnts', '25')
               ->pause('1000')
                  ->type('credit_score', '500')
             ->select('sub_status_flag', '1')
             ->select('industry_id', '8')
             ->select('sub_status_id', '1')
             ->select('advance_type', 'Daily ACH')
             ->select('marketplace_status', '0')
             ->select('source_id', '1')

             ->select('lender_id', '24')
             ->select('label', '4')
             // ->radio('m_s_prepaid_status', '2')
             // ->select('underwriting_fee', '1.75')
             // ->check('underwriting_status[]', '1')
             // ->check('underwriting_status[]', '2')
             ->pause('2000')
             // ->check('email_notification')
       ->check('ach_pull')
          ->pause('6000')
            ->type('account_holder_name', 'federal')
             ->pause('2000')

            ->type('routing_number', '122105155')
             ->pause('3000')
            ->type('account_number', '00012345908678')
            ->clickLink('Confirm')
            ->pause('4000')
             ->press('Create')
             ->pause('6000')
             ->press('×');

        $this->browser->visit('/admin/merchants/create')
             ->type('name', 'iocod15')
             ->type('first_name', 'merch15')
             ->type('last_name', 'test15')
           ->select('state_id', '9')
              ->select('industry_id', '8')
             // ->type('email','iocod481@yahoo.in')
             // ->check('email_notification')

             ->type('merchant_email', 'test15@gmail.com')
                ->pause('1000')
             ->type('date_funded1', '04-05-2020')
                ->pause('6000')
             ->type('funded', '10000')
             ->pause('6000')
              ->pause('6000')
             ->type('max_participant_fund_per', '100')
             ->pause('6000')
              ->pause('6000')
             ->type('company_per[3]', '50')
             ->pause('6000')
             ->type('company_per[4]', '0')
             ->type('company_per[5]', '50')
             ->pause('6000')
             ->type('factor_rate', '1.8')
             ->type('commission', '18')
             ->type('pmnts', '20')
               ->pause('1000')
                  ->type('credit_score', '500')
             ->select('sub_status_flag', '1')

             ->select('sub_status_id', '1')
             ->select('advance_type', 'Daily ACH')
             ->select('marketplace_status', '0')
             ->select('source_id', '1')

             ->select('lender_id', '24')
             // ->select('label','4')
             // ->radio('m_s_prepaid_status', '2')
             // ->select('underwriting_fee', '1.75')
             // ->check('underwriting_status[]', '1')
             // ->check('underwriting_status[]', '2')
             ->pause('2000')
             // ->check('email_notification')
         ->check('ach_pull')
          ->pause('6000')
            ->type('account_holder_name', 'federal')
             ->pause('2000')

            ->type('routing_number', '122105155')
             ->pause('3000')
            ->type('account_number', '00012345908678')
            ->clickLink('Confirm')
            ->pause('4000')

             ->press('Create')
             ->pause('6000')
             ->press('×');

        $this->browser->visit('/admin/merchants/create')
             ->type('name', 'iocod16')
             ->type('first_name', 'merch16')
             ->type('last_name', 'test16')
             ->select('industry_id', '8')
              ->select('state_id', '9')
             // ->type('email','iocod481@yahoo.in')
             // ->check('email_notification')

             ->type('merchant_email', 'test16@gmail.com')
                ->pause('1000')
             ->type('date_funded1', '05-05-2020')
                ->pause('6000')
             ->type('funded', '25600')
             ->pause('6000')
              ->pause('6000')
             ->type('max_participant_fund_per', '100')
             ->pause('6000')
              ->pause('6000')
             ->type('company_per[3]', '50')
             ->pause('6000')
             ->type('company_per[4]', '30')
                ->pause('6000')
              ->type('company_per[5]', '20')
             ->pause('6000')
             ->type('factor_rate', '1.8')
             ->type('commission', '15')
             ->type('pmnts', '10')
               ->pause('1000')
                  ->type('credit_score', '500')
             ->select('sub_status_flag', '1')

             ->select('sub_status_id', '1')
             ->select('advance_type', 'Daily ACH')
             ->select('marketplace_status', '0')
             ->select('source_id', '1')

             ->select('lender_id', '24')
             // ->select('label','4')
             // ->radio('m_s_prepaid_status', '2')
             // ->select('underwriting_fee', '1.75')
             // ->check('underwriting_status[]', '1')
             // ->check('underwriting_status[]', '2')
             ->pause('2000')
             // ->check('email_notification')

           ->check('ach_pull')
          ->pause('6000')
            ->type('account_holder_name', 'federal')
             ->pause('2000')

            ->type('routing_number', '122105155')
             ->pause('3000')
            ->type('account_number', '00012345908678')
            ->clickLink('Confirm')
            ->pause('4000')

             ->press('Create')
             ->pause('6000')
             ->press('×');
    }

    public function assign()
    {
        $this->browser->visit('/admin/merchants/view/1')
                      ->clickLink('Assign Investors')
                      ->select('company', 'All')
                      ->pause('6000')
                      ->press('Assign')
                      ->pause('6000');

        $this->browser->visit('/admin/merchants/view/2')
                      ->clickLink('Assign Investors')
                      ->select('company', 'All')
                      ->pause('6000')
                      ->press('Assign')
                      ->pause('6000');

        $this->browser->visit('/admin/merchants/view/3')
                      ->clickLink('Assign Investors')
                      ->select('company', 'All')
                      ->pause('6000')
                      ->press('Assign')
                      ->pause('6000');

        $this->browser->visit('/admin/merchants/view/4')
                      ->clickLink('Assign Investors')
                      ->select('company', 'All')
                      ->pause('6000')
                      ->press('Assign')
                      ->pause('6000');

        $this->browser->visit('/admin/merchants/view/5')
                      ->clickLink('Assign Investors')
                      ->select('company', 'All')
                      ->pause('6000')
                      ->press('Assign')
                      ->pause('6000');

        $this->browser->visit('/admin/merchants/view/6')
                      ->clickLink('Assign Investors')
                      ->select('company', 'All')
                      ->pause('6000')
                      ->press('Assign')
                      ->pause('6000');

        $this->browser->visit('/admin/merchants/view/7')
                      ->clickLink('Assign Investors')
                      ->select('company', 'All')
                      ->pause('6000')
                      ->press('Assign')
                      ->pause('6000');

        $this->browser->visit('/admin/merchants/view/8')
                      ->clickLink('Assign Investors')
                      ->select('company', 'All')
                      ->pause('6000')
                      ->press('Assign')
                      ->pause('6000');

        $this->browser->visit('/admin/merchants/view/9')
                      ->clickLink('Assign Investors')
                      ->select('company', 'All')
                      ->pause('6000')
                      ->press('Assign')
                      ->pause('6000');

        $this->browser->visit('/admin/merchants/view/10')
                      ->clickLink('Assign Investors')
                      ->select('company', 'All')
                      ->pause('6000')
                      ->press('Assign')
                      ->pause('6000');

        //     $this->browser->visit('/admin/merchants/view/11')
        //                ->clickLink('Assign Investors')
        //                ->select('company', 'All')
        //                ->pause('6000')
        //                ->press('Assign')
        //                ->pause('6000');

        //    $this->browser->visit('/admin/merchants/view/12')
        //                ->clickLink('Assign Investors')
        //                ->select('company', 'All')
        //                ->pause('6000')
        //                ->press('Assign')
        //                ->pause('6000');

        $this->browser->visit('/admin/merchants/view/13')
                      ->clickLink('Assign Investors')
                      ->select('company', 'All')
                      ->pause('6000')
                      ->press('Assign')
                      ->pause('6000');

        //    $this->browser->visit('/admin/merchants/view/14')
        //                ->clickLink('Assign Investors')
        //                ->select('company', 'All')
        //                ->pause('6000')
        //                ->press('Assign')
        //                ->pause('6000');

        $this->browser->visit('/admin/merchants/view/15')
                      ->clickLink('Assign Investors')
                      ->select('company', 'All')
                      ->pause('6000')
                      ->press('Assign')
                      ->pause('6000');

        $this->browser->visit('/admin/merchants/view/16')
                      ->clickLink('Assign Investors')
                      ->select('company', 'All')
                      ->pause('6000')
                      ->press('Assign')
                      ->pause('6000');

        $this->browser->visit('/admin/dashboard')
                    ->assertPathIs('/admin/dashboard')
                     ->pause('12000')
                      ->pause('12000')
                      ->pause('6000');
    }

    public function payment()
    {
        // $this->browser->visit('/admin/merchants/view/1')
        //         ->clickLink('Add Payment')
        //          ->visit('admin/payment/create/1')
        //         ->press('Select All Investors')
        //         ->pause('6000')
        //         ->type('payment_date1', '04-01-2021,04-02-2021')
        //         ->pause('6000')
        //         ->press('Create')
        //         ->pause('6000')
        //         ->visit('/admin/payment/create/1');

        $this->browser->visit('/admin/merchants/view/2')
                   ->clickLink('Add Payment')
                    ->visit('admin/payment/create/2')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-01-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/2');

        $this->browser->visit('/admin/merchants/view/3')
                   ->clickLink('Add Payment')
                   ->visit('admin/payment/create/3')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-01-2021,04-02-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/3');

        $this->browser->visit('/admin/merchants/view/4')
                   ->clickLink('Add Payment')
                   ->visit('admin/payment/create/4')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-01-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/4');

        $this->browser->visit('/admin/merchants/view/5')
                   ->clickLink('Add Payment')
                   ->visit('admin/payment/create/5')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-01-2021,04-02-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/5');

        $this->browser->visit('/admin/merchants/view/6')
                   ->clickLink('Add Payment')
                   ->visit('admin/payment/create/6')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-01-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/6');

        $this->browser->visit('/admin/merchants/view/7')
                   ->clickLink('Add Payment')
                   ->visit('admin/payment/create/7')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-01-2021,04-02-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/7');

        $this->browser->visit('/admin/merchants/view/8')
                   ->clickLink('Add Payment')
                   ->visit('admin/payment/create/8')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-01-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/8');

        $this->browser->visit('/admin/merchants/view/9')
                   ->clickLink('Add Payment')
                   ->visit('admin/payment/create/9')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-01-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/9');

        $this->browser->visit('/admin/merchants/view/10')
                   ->clickLink('Add Payment')
                   ->visit('admin/payment/create/10')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-01-2021,04-02-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/10');

        // $this->browser->visit('/admin/merchants/view/11')
        //                 ->clickLink('Add Payment')
        //                 ->visit('admin/payment/create/11')
        //                 ->press('Select All Investors')
        //                 ->pause('6000')
        //                 ->type('payment_date1', '04-01-2021')
        //                 ->pause('6000')
        //                 ->press('Create')
        //                 ->pause('6000')
        //                 ->visit('/admin/payment/create/11');

        $this->browser->visit('/admin/merchants/view/13')
                   ->clickLink('Add Payment')
                   ->visit('admin/payment/create/13')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-01-2021,04-02-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/13');

        $this->browser->visit('/admin/merchants/view/15')
                   ->clickLink('Add Payment')
                   ->visit('admin/payment/create/15')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-01-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/15');

        $this->browser->visit('/admin/merchants/view/16')
                   ->clickLink('Add Payment')
                   ->visit('admin/payment/create/16')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-01-2021,04-02-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/16');

        $this->browser->visit('/admin/dashboard')
                    ->assertPathIs('/admin/dashboard')
                     ->pause('12000')
                      ->pause('12000')
                      ->pause('6000');

        $this->browser
                       ->visit('/admin/merchants/edit/1')
                       ->pause('6000')
                       ->select('sub_status_id', '4')
                       ->press('Update')
                       ->pause('6000')
                       ->assertPathIs('/admin/merchants/edit/1');
        $this->browser
                       ->visit('/admin/merchants/edit/3')
                       ->pause('6000')
                       ->select('sub_status_id', '4')
                       ->press('Update')
                       ->pause('6000')
                       ->assertPathIs('/admin/merchants/edit/3');

        $this->browser
                       ->visit('/admin/merchants/edit/2')
                       ->pause('6000')
                       ->select('sub_status_id', '4')
                       ->press('Update')
                       ->pause('6000')
                       ->assertPathIs('/admin/merchants/edit/2');

        $this->browser->visit('/admin/dashboard')
                    ->assertPathIs('/admin/dashboard')
                     ->pause('12000')
                     ->pause('12000')
                      ->pause('6000');

        $this->browser
                       ->visit('/admin/merchants/edit/2')
                       ->pause('6000')
                       ->select('sub_status_id', '5')
                       ->press('Update')
                       ->pause('6000')
                       ->assertPathIs('/admin/merchants/edit/2');

        $this->browser->visit('/admin/dashboard')
                    ->assertPathIs('/admin/dashboard')
                     ->pause('12000')
                     ->pause('12000')
                      ->pause('6000');

        $this->browser->visit('/admin/merchants/view/2')
                   ->clickLink('Add Payment')
                    ->visit('admin/payment/create/2')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-05-2021,04-06-2021,04-07-2021,04-09-2021,04-11-2021,04-12-2021,04-13-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/2');

        $this->browser->visit('/admin/merchants/view/4')
                   ->clickLink('Add Payment')
                    ->visit('admin/payment/create/4')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-05-2021,04-06-2021,04-07-2021,04-09-2021,04-11-2021,04-12-2021,04-13-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/4');

        $this->browser->visit('/admin/merchants/view/5')
                   ->clickLink('Add Payment')
                    ->visit('admin/payment/create/5')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-05-2021,04-06-2021,04-07-2021,04-09-2021,04-11-2021,04-12-2021,04-13-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/5');

        $this->browser->visit('/admin/merchants/view/6')
                   ->clickLink('Add Payment')
                    ->visit('admin/payment/create/6')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-05-2021,04-06-2021,04-07-2021,04-09-2021,04-11-2021,04-12-2021,04-13-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/6');

        $this->browser->visit('/admin/merchants/view/7')
                   ->clickLink('Add Payment')
                    ->visit('admin/payment/create/7')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-05-2021,04-06-2021,04-07-2021,04-09-2021,04-11-2021,04-12-2021,04-13-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/7');

        $this->browser->visit('/admin/merchants/view/8')
                   ->clickLink('Add Payment')
                    ->visit('admin/payment/create/8')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-05-2021,04-06-2021,04-07-2021,04-09-2021,04-11-2021,04-12-2021,04-13-2021')
                  ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/8');

        $this->browser->visit('/admin/merchants/view/9')
                   ->clickLink('Add Payment')
                    ->visit('admin/payment/create/9')
                   ->press('Select All Investors')
                   ->pause('6000')
                  ->type('payment_date1', '04-05-2021,04-06-2021,04-07-2021,04-09-2021,04-11-2021,04-12-2021,04-13-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/9');

        $this->browser->visit('/admin/merchants/view/10')
                   ->clickLink('Add Payment')
                    ->visit('admin/payment/create/10')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-05-2021,04-06-2021,04-07-2021,04-09-2021,04-11-2021,04-12-2021,04-13-2021')
                 ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/10');

        // $this->browser->visit('/admin/merchants/view/11')
        //              ->clickLink('Add Payment')
        //               ->visit('admin/payment/create/11')
        //              ->press('Select All Investors')
        //              ->pause('6000')
        //              ->type('payment_date1', '04-05-2021,2020-06-05,04-07-2021,04-09-2021,04-11-2021,04-12-2021,04-13-2021')
        //              ->pause('6000')
        //              ->press('Create')
        //              ->pause('6000')
        //              ->visit('/admin/payment/create/11');

        $this->browser->visit('/admin/merchants/view/13')
                   ->clickLink('Add Payment')
                    ->visit('admin/payment/create/13')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-05-2021,2020-06-05,04-07-2021,04-09-2021,04-11-2021,04-12-2021,04-13-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/13');

        $this->browser->visit('/admin/merchants/view/15')
                   ->clickLink('Add Payment')
                    ->visit('admin/payment/create/15')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-05-2021,04-06-2021,04-07-2021,04-09-2021,04-11-2021,04-12-2021,04-13-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/15');

        $this->browser->visit('/admin/merchants/view/16')
                   ->clickLink('Add Payment')
                    ->visit('admin/payment/create/16')
                   ->press('Select All Investors')
                   ->pause('6000')
                   ->type('payment_date1', '04-05-2021,04-06-2021,04-07-2021,04-09-2021,04-11-2021,04-12-2021,04-13-2021')
                   ->pause('6000')
                   ->press('Create')
                   ->pause('6000')
                   ->visit('/admin/payment/create/16');
    }
}
