<?php

namespace Tests\Unit\Http\Requests\Admin;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\Admin\RunCommandsAdminUserRequest
 */
class RunCommandsAdminUserRequestTest extends TestCase
{
    /** @var \App\Http\Requests\Admin\RunCommandsAdminUserRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\Admin\RunCommandsAdminUserRequest();
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'command' => [
                'required',
                'string',
                'min:2',
            ],
        ], $actual);
    }

    // test cases...
}
