<?php

namespace Tests\Unit\Http\Requests\Admin;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\Admin\StoreFaqMerchantRequest
 */
class StoreFaqMerchantRequestTest extends TestCase
{
    /** @var \App\Http\Requests\Admin\StoreFaqMerchantRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\Admin\StoreFaqMerchantRequest();
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'description' => [
                'required',
            ],
            'title' => [
                'required',
            ],
        ], $actual);
    }

    // test cases...
}
