# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: lorisleiva/laravel-docker

pipelines:
  branches:
    release/uat:
        - step:
            name: deploy_to_uat
            script:
                - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
                - cp .env.example .env
                - cp .env.testing.example .env.testing
                - composer dump-autoload
                - php artisan migrate:fresh --seed
                - php artisan db:seed --class=View
                - php artisan key:generate
                - php artisan optimize:clear
                - php artisan passport:install
                - php artisan test
  default:
    - parallel:
        - step:
            name: Test
            script:
              - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
              - cp .env.example .env
              - composer dump-autoload
              - cp .env.testing.example .env.testing
              - php artisan migrate:fresh --seed
              - php artisan key:generate
              - php artisan optimize:clear 


  