<?php

namespace Tests\Unit\Http\Requests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\AdminFirewall
 */
class AdminFirewallTest extends TestCase
{
    /** @var \App\Http\Requests\AdminFirewall */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\AdminFirewall();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules_asdfasdf()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'user_id' => [
                'required',
                'exists:users,id',
            ],
            'ip_address' => [
                'required',
                'ip',
            ],
        ], $actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'user_id' => [
                'required',
                'exists:users,id',
            ],
            'ip_address' => [
                'required',
                'ip',
                'exists:firewalls,ip_address',
            ],
        ], $actual);
    }

    // test cases...
}
