<?php

namespace Tests\Unit\Http\Requests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\AdminBills
 */
class AdminBillsTest extends TestCase
{
    /** @var \App\Http\Requests\AdminBills */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\AdminBills();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'amount' => [
                'required',
                'regex:/^[\d\s,-.]*$/',
            ],
        ], $actual);
    }

    /**
     * @test
     */
    public function rules_not_sure_why_added()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'amount' => [
                'required',
            ],
            'investor_id' => [
                'required',
            ],
            'date' => [
                'required',
            ],
            'account_no' => [
                'required',
            ],
        ], $actual);
    }

    // test cases...
}
