<?php

namespace Tests\Feature\Http\Controllers\Investor;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Investor\StatementController
 */
class StatementControllerTest extends TestCase
{
    /**
     * @test
     */
    public function view_weekly_report_document_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('investor::statements::weekly-view', ['id' => $id]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function weekly_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('investor::statements::weekly'));

        $response->assertOk();
        $response->assertViewIs('investor.statement.index');
        $response->assertViewHas('statements');
        $response->assertViewHas('page_title');

        // TODO: perform additional assertions
    }

    // test cases...
}
