<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AdminViewController
 */
class AdminViewControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        // $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        // $response = $this->get('v/admin/{any?}');

        // $response->assertOk();
        // $response->assertViewIs('vue.admin');
        // $response->assertViewHas('authToken');

        // TODO: perform additional assertions
    }

    // test cases...
}
