<?php

namespace Tests\Feature\Http\Controllers\Api\Admin;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Api\Admin\MerchantLogController
 */
class MerchantLogControllerTest extends TestCase
{
    /**
     * @test
     */
    public function get_status_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('api/admin/merchant-log/status');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
