describe('Tests for lenders', () => {
    beforeEach(() => {
        cy.login({ email: 'admin@investor.portal' })
        cy.visit('/admin/lender/create')
    })
    it('Verify if `create lender` page is accessable', () => {
        cy.get('.wrapper.demo > div.content-wrapper > section.content > div.inner.admin-dsh.header-tp > h3').contains('Create New Lender ')
    })
    it('Create `LenderA` lender', () => {
        cy.get('#lenderNameId').type('LenderA')
        cy.get('[name="email"]').type('lendera@gmail.com')
        cy.get('[name="password"]').type('123123')
        cy.get('[name="password_confirmation"]').type('123123')
        cy.get('[name="management_fee"]').select('3.00', { force: true })
        cy.get('[name="global_syndication"]').select('0.00', { force: true })
        cy.get('#underwriting_fee').select('0.00', { force: true })
        cy.get('[name="lag_time"]').type('10')
        cy.get('[value="Create"]').click()
        cy.get('body > div.wrapper.demo > div.content-wrapper > section.content > div.col-md-12 > div > div > div.box-body.alert-box-body > div').invoke('text')
            .should('match', /New Lender Created/i)

    })

    it('Create `LenderB` lender', () => {
        cy.get('#lenderNameId').type('LenderB')
        cy.get('[name="email"]').type('lenderb@gmail.com')
        cy.get('[name="password"]').type('123123')
        cy.get('[name="password_confirmation"]').type('123123')
        cy.get('[name="management_fee"]').select('3.00', { force: true })
        cy.get('[name="global_syndication"]').select('2.00', { force: true })
        cy.get('[name="s_prepaid_status"]').check('2')
        cy.get('#underwriting_fee').select('0.00', { force: true })
        cy.get('[name="lag_time"]').type('3')
        cy.get('[value="Create"]').click()
        cy.get('body > div.wrapper.demo > div.content-wrapper > section.content > div.col-md-12 > div > div > div.box-body.alert-box-body > div').invoke('text')
            .should('match', /New Lender Created/i)
    })

    it('Create `LenderC` lender', () => {
        cy.get('#lenderNameId').type('LenderC')
        cy.get('[name="email"]').type('lenderc@gmail.com')
        cy.get('[name="password"]').type('123123')
        cy.get('[name="password_confirmation"]').type('123123')
        cy.get('[name="management_fee"]').select('0.00', { force: true })
        cy.get('[name="global_syndication"]').select('2.00', { force: true })
        cy.get('[name="s_prepaid_status"]').check('2')
        cy.get('#underwriting_fee').select('0.00', { force: true })
        cy.get('[name="lag_time"]').type('5')
        cy.get('[value="Create"]').click()
        cy.get('body > div.wrapper.demo > div.content-wrapper > section.content > div.col-md-12 > div > div > div.box-body.alert-box-body > div').invoke('text')
            .should('match', /New Lender Created/i)
    })

    it('Create `LenderD` lender', () => {
        cy.get('#lenderNameId').type('LenderD')
        cy.get('[name="email"]').type('lenderd@gmail.com')
        cy.get('[name="password"]').type('123123')
        cy.get('[name="password_confirmation"]').type('123123')
        cy.get('[name="management_fee"]').select('2.00', { force: true })
        cy.get('[name="global_syndication"]').select('1.00', { force: true })
        cy.get('[name="s_prepaid_status"]').check('2')
        cy.get('#underwriting_fee').select('0.00', { force: true })
        cy.get('[name="lag_time"]').type('14')
        cy.get('[value="Create"]').click()
        cy.get('body > div.wrapper.demo > div.content-wrapper > section.content > div.col-md-12 > div > div > div.box-body.alert-box-body > div').invoke('text')
            .should('match', /New Lender Created/i)
    })

    it('Create `LenderE` lender', () => {
        cy.get('#lenderNameId').type('LenderE')
        cy.get('[name="email"]').type('lendere@gmail.com')
        cy.get('[name="password"]').type('123123')
        cy.get('[name="password_confirmation"]').type('123123')
        cy.get('[name="management_fee"]').select('3.00', { force: true })
        cy.get('[name="global_syndication"]').select('2.50', { force: true })
        cy.get('[name="s_prepaid_status"]').check('2')
        cy.get('#underwriting_fee').select('0.00', { force: true })
        cy.get('[name="lag_time"]').type('14')
        cy.get('[value="Create"]').click()
        cy.get('body > div.wrapper.demo > div.content-wrapper > section.content > div.col-md-12 > div > div > div.box-body.alert-box-body > div').invoke('text')
            .should('match', /New Lender Created/i)
    })
})