describe('Tests for creating merchants', () => {
    beforeEach(() => {
        cy.login({ email: 'admin@investor.portal' })
        cy.visit('/admin/merchants/create')
    })
    it('Verify if `create merchants` page accessable', () => {
        cy.get('.wrapper.demo > div.content-wrapper > section.content > div.inner.admin-dsh.header-tp > h3').contains('Add Merchant ')
    })
    it('Creates merchant `iocod1`', () => {
        cy.get('[name="name"]').type('iocod1')
        cy.get('[name="first_name"]').type('iocod1')
        cy.get('[name="state_id"]').select('3', { force: true })
        cy.get('[name="industry_id"]').select('32', { force: true })
        cy.get('[name="merchant_email"]').type('test1@gmail.com')
        cy.get('[name="date_funded1"]').type('03-05-2020')
        cy.get('[name="funded"]').clear().type('25000')
        cy.get('[name="max_participant_fund_per"]').type('100', { force: true })
        cy.get('#company_max_1').clear().type('12500')
        cy.get('#company_max_2').clear().type('12500')
        cy.get('[name="factor_rate"]').type('1.3')
        cy.get('[name="commission"]').type('10')
        cy.get('[name="pmnts"]').type('10')
        cy.get('[name="credit_score"]').type('500')
        // cy.get('[name="sub_status_flag"]').select('1', { force: true })
        cy.get('[name="sub_status_id"]').select('1', { force: true })
        cy.get('[name="advance_type"]').select('Daily ACH', { force: true })
        cy.get('[name="marketplace_status"]').select('0', { force: true })
        cy.get('[name="source_id"]').select('1', { force: true })
        cy.get('[name="lender_id"]').select('LenderA', { force: true })
        cy.get('[name="m_s_prepaid_status"]').check('2')
        cy.get('[name="underwriting_fee"]').select('1.75', { force: true })
        cy.get('[name="underwriting_status[]"]').check('1')
        cy.get('[name="underwriting_status[]"]').check('2')
        cy.get('[name="ach_pull"]').check()
        cy.get('[name="account_holder_name"]').type('federal')
        cy.get('[name="routing_number"]').type('082000549')
        cy.get('[name="account_number"]').type('0001234005678')
        cy.get('#bankAcoountModalSubmit').click()
        cy.get('#merchant_create_form').submit();
        cy.get('.wrapper.demo > div.content-wrapper > section.content > div.col-md-12 > div > div.box-head > div > div > h4').invoke('text')
            .should('match', / Success/i)
    })

    it('Creates merchant `iocod2`', () => {
        cy.get('[name="name"]').type('iocod2')
        cy.get('[name="first_name"]').type('iocod2')
        cy.get('[name="state_id"]').select('5', { force: true })
        cy.get('[name="industry_id"]').select('1', { force: true })
        cy.get('[name="merchant_email"]').type('test2@gmail.com')
        cy.get('[name="date_funded1"]').type('04-01-2021')
        cy.get('[name="funded"]').clear().type('10050')
        cy.get('[name="max_participant_fund_per"]').type('100', { force: true })
        cy.get('#company_max_1').clear().type('2060.25')
        cy.get('#company_max_2').clear().type('2060.25')
        cy.get('#company_max_3').clear().type('5929.5')
        cy.get('[name="factor_rate"]').type('1.5')
        cy.get('[name="commission"]').type('8.5')
        cy.get('[name="pmnts"]').type('10')
        cy.get('[name="credit_score"]').type('580')
        // cy.get('[name="sub_status_flag"]').select('1', { force: true })
        cy.get('[name="sub_status_id"]').select('1', { force: true })
        cy.get('[name="advance_type"]').select('Weekly ACH', { force: true })
        cy.get('[name="marketplace_status"]').select('0', { force: true })
        cy.get('[name="source_id"]').select('1', { force: true })
        cy.get('[name="lender_id"]').select('LenderB', { force: true })
        cy.get('[name="m_s_prepaid_status"]').check('2')
        // cy.get('[name="underwriting_fee"]').select('1.75', { force: true })
        cy.get('[name="underwriting_status[]"]').check('1')
        cy.get('[name="underwriting_status[]"]').check('2')
        cy.get('[name="ach_pull"]').check()
        cy.get('[name="account_holder_name"]').type('federal')
        cy.get('[name="routing_number"]').type('121122676')
        cy.get('[name="account_number"]').type('002569786122')
        cy.get('#bankAcoountModalSubmit').click()
        cy.get('#merchant_create_form').submit();
        cy.get('.wrapper.demo > div.content-wrapper > section.content > div.col-md-12 > div > div.box-head > div > div > h4').invoke('text')
            .should('match', / Success/i)
    })

    it('Creates merchant `iocod3`', () => {
        cy.get('[name="name"]').type('iocod3')
        cy.get('[name="first_name"]').type('merch3')
        cy.get('[name="state_id"]').select('4', { force: true })
        cy.get('[name="industry_id"]').select('2', { force: true })
        cy.get('[name="merchant_email"]').type('test3@gmail.com')
        cy.get('[name="date_funded1"]').type('03-30-2021')
        cy.get('[name="funded"]').clear().type('25000')
        cy.get('[name="max_participant_fund_per"]').type('100', { force: true })
        cy.get('#company_max_1').clear().type('8332.5')
        cy.get('#company_max_2').clear().type('16667.5')
        cy.get('[name="factor_rate"]').type('1.77')
        cy.get('[name="commission"]').type('15')
        cy.get('[name="pmnts"]').type('15')
        cy.get('[name="credit_score"]').type('520')
        // cy.get('[name="sub_status_flag"]').select('1', { force: true })
        cy.get('[name="sub_status_id"]').select('1', { force: true })
        cy.get('[name="advance_type"]').select('Daily ACH', { force: true })
        cy.get('[name="marketplace_status"]').select('0', { force: true })
        cy.get('[name="source_id"]').select('2', { force: true })
        cy.get('[name="lender_id"]').select('LenderC', { force: true })
        // cy.get('[name="m_s_prepaid_status"]').check('2')
        // cy.get('[name="underwriting_fee"]').select('1.75', { force: true })
        // cy.get('[name="underwriting_status[]"]').check('1')
        // cy.get('[name="underwriting_status[]"]').check('2')
        cy.get('[name="ach_pull"]').check()
        cy.get('[name="account_holder_name"]').type('federal')
        cy.get('[name="routing_number"]').type('122235821')
        cy.get('[name="account_number"]').type('234500001234')
        cy.get('#bankAcoountModalSubmit').click()
        cy.get('#merchant_create_form').submit();
        cy.get('.wrapper.demo > div.content-wrapper > section.content > div.col-md-12 > div > div.box-head > div > div > h4').invoke('text')
            .should('match', / Success/i)
    })

    it('Creates merchant `iocod4`', () => {
        cy.get('[name="name"]').type('iocod4')
        cy.get('[name="first_name"]').type('merch4')
        cy.get('[name="state_id"]').select('1', { force: true })
        cy.get('[name="industry_id"]').select('3', { force: true })
        cy.get('[name="merchant_email"]').type('test4@gmail.com')
        cy.get('[name="date_funded1"]').type('05-05-2020')
        cy.get('[name="funded"]').clear().type('55000')
        cy.get('[name="max_participant_fund_per"]').type('25', { force: true })
        cy.get('#company_max_1').clear().type('2552')
        cy.get('#company_max_2').clear().type('5599')
        cy.get('#company_max_3').clear().type('5599')
        cy.get('[name="factor_rate"]').type('1.9')
        cy.get('[name="commission"]').type('20')
        cy.get('[name="pmnts"]').type('20')
        cy.get('[name="credit_score"]').type('500')
        // cy.get('[name="sub_status_flag"]').select('1', { force: true })
        cy.get('[name="sub_status_id"]').select('1', { force: true })
        cy.get('[name="advance_type"]').select('Weekly ACH', { force: true })
        cy.get('[name="marketplace_status"]').select('0', { force: true })
        cy.get('[name="source_id"]').select('1', { force: true })
        cy.get('[name="lender_id"]').select('LenderD', { force: true })
        // cy.get('[name="m_s_prepaid_status"]').check('2')
        // cy.get('[name="underwriting_fee"]').select('1.75', { force: true })
        // cy.get('[name="underwriting_status[]"]').check('1')
        // cy.get('[name="underwriting_status[]"]').check('2')
        cy.get('[name="ach_pull"]').check()
        cy.get('[name="account_holder_name"]').type('federal')
        cy.get('[name="routing_number"]').type('082000549')
        cy.get('[name="account_number"]').type('000123000045678')
        cy.get('#bankAcoountModalSubmit').click()
        cy.get('#merchant_create_form').submit();
        cy.get('.wrapper.demo > div.content-wrapper > section.content > div.col-md-12 > div > div.box-head > div > div > h4').invoke('text')
            .should('match', / Success/i)
    })

    it('Creates merchant `iocod5`', () => {
        cy.get('[name="name"]').type('iocod5')
        cy.get('[name="first_name"]').type('merch5')
        cy.get('[name="state_id"]').select('2', { force: true })
        cy.get('[name="industry_id"]').select('4', { force: true })
        cy.get('[name="merchant_email"]').type('test5@gmail.com')
        cy.get('[name="date_funded1"]').type('03-01-2021')
        cy.get('[name="funded"]').clear().type('80500')
        cy.get('[name="max_participant_fund_per"]').type('50', { force: true })
        cy.get('#company_max_1').clear().type('20125')
        cy.get('#company_max_2').clear().type('20125')
        cy.get('[name="factor_rate"]').type('1.88')
        cy.get('[name="commission"]').type('14')
        cy.get('[name="pmnts"]').type('20')
        cy.get('[name="credit_score"]').type('500')
        // cy.get('[name="sub_status_flag"]').select('1', { force: true })
        cy.get('[name="sub_status_id"]').select('1', { force: true })
        cy.get('[name="advance_type"]').select('Daily ACH', { force: true })
        cy.get('[name="marketplace_status"]').select('0', { force: true })
        cy.get('[name="source_id"]').select('1', { force: true })
        cy.get('[name="lender_id"]').select('LenderE', { force: true })
        // cy.get('[name="m_s_prepaid_status"]').check('2')
        // cy.get('[name="underwriting_fee"]').select('1.75', { force: true })
        // cy.get('[name="underwriting_status[]"]').check('1')
        // cy.get('[name="underwriting_status[]"]').check('2')
        cy.get('[name="ach_pull"]').check()
        cy.get('[name="account_holder_name"]').type('federal')
        cy.get('[name="routing_number"]').type('122235821')
        cy.get('[name="account_number"]').type('000004547678758')
        cy.get('#bankAcoountModalSubmit').click()
        cy.get('#merchant_create_form').submit();
        cy.get('.wrapper.demo > div.content-wrapper > section.content > div.col-md-12 > div > div.box-head > div > div > h4').invoke('text')
            .should('match', / Success/i)
    })

    it('Creates merchant `iocod6`', () => {
        cy.get('[name="name"]').type('iocod6')
        cy.get('[name="first_name"]').type('merch6')
        cy.get('[name="state_id"]').select('6', { force: true })
        cy.get('[name="industry_id"]').select('5', { force: true })
        cy.get('[name="merchant_email"]').type('test6@gmail.com')
        cy.get('[name="date_funded1"]').type('01-05-2021')
        cy.get('[name="funded"]').clear().type('10000')
        cy.get('[name="max_participant_fund_per"]').type('80', { force: true })
        cy.get('#company_max_1').clear().type('4000')
        cy.get('#company_max_2').clear().type('2000')
        cy.get('#company_max_3').clear().type('2000')
        cy.get('[name="factor_rate"]').type('1.66')
        cy.get('[name="commission"]').type('15')
        cy.get('[name="pmnts"]').type('25')
        cy.get('[name="credit_score"]').type('500')
        // cy.get('[name="sub_status_flag"]').select('1', { force: true })
        cy.get('[name="sub_status_id"]').select('1', { force: true })
        cy.get('[name="advance_type"]').select('Weekly ACH', { force: true })
        cy.get('[name="marketplace_status"]').select('0', { force: true })
        cy.get('[name="source_id"]').select('1', { force: true })
        cy.get('[name="lender_id"]').select('LenderA', { force: true })
        // cy.get('[name="m_s_prepaid_status"]').check('2')
        // cy.get('[name="underwriting_fee"]').select('1.75', { force: true })
        // cy.get('[name="underwriting_status[]"]').check('1')
        // cy.get('[name="underwriting_status[]"]').check('2')
        cy.get('[name="ach_pull"]').check()
        cy.get('[name="account_holder_name"]').type('federal')
        cy.get('[name="routing_number"]').type('082000549')
        cy.get('[name="account_number"]').type('000123451111678')
        cy.get('#bankAcoountModalSubmit').click()
        cy.get('#merchant_create_form').submit();
        cy.get('.wrapper.demo > div.content-wrapper > section.content > div.col-md-12 > div > div.box-head > div > div > h4').invoke('text')
            .should('match', / Success/i)
    })

    it('Creates merchant `iocod7`', () => {
        cy.get('[name="name"]').type('iocod7')
        cy.get('[name="first_name"]').type('merch7')
        cy.get('[name="state_id"]').select('7', { force: true })
        cy.get('[name="industry_id"]').select('6', { force: true })
        cy.get('[name="merchant_email"]').type('test7@gmail.com')
        cy.get('[name="date_funded1"]').type('02-25-2021')
        cy.get('[name="funded"]').clear().type('20000')
        cy.get('[name="max_participant_fund_per"]').type('100', { force: true })
        cy.get('#company_max_1').clear().type('5000')
        cy.get('#company_max_2').clear().type('15000')
        cy.get('[name="factor_rate"]').type('1.56')
        cy.get('[name="commission"]').type('14')
        cy.get('[name="pmnts"]').type('36')
        cy.get('[name="credit_score"]').type('500')
        // cy.get('[name="sub_status_flag"]').select('1', { force: true })
        cy.get('[name="sub_status_id"]').select('1', { force: true })
        cy.get('[name="advance_type"]').select('Daily ACH', { force: true })
        cy.get('[name="marketplace_status"]').select('0', { force: true })
        cy.get('[name="source_id"]').select('1', { force: true })
        cy.get('[name="lender_id"]').select('LenderB', { force: true })
        // cy.get('[name="m_s_prepaid_status"]').check('2')
        // cy.get('[name="underwriting_fee"]').select('1.75', { force: true })
        // cy.get('[name="underwriting_status[]"]').check('1')
        // cy.get('[name="underwriting_status[]"]').check('2')
        cy.get('[name="ach_pull"]').check()
        cy.get('[name="account_holder_name"]').type('federal')
        cy.get('[name="routing_number"]').type('122235821')
        cy.get('[name="account_number"]').type('334455667710')
        cy.get('#bankAcoountModalSubmit').click()
        cy.get('#merchant_create_form').submit();
        cy.get('.wrapper.demo > div.content-wrapper > section.content > div.col-md-12 > div > div.box-head > div > div > h4').invoke('text')
            .should('match', / Success/i)
    })
    it('Creates merchant `iocod8`', () => {
        cy.get('[name="name"]').type('iocod8')
        cy.get('[name="first_name"]').type('merch8')
        cy.get('[name="state_id"]').select('8', { force: true })
        cy.get('[name="industry_id"]').select('7', { force: true })
        cy.get('[name="merchant_email"]').type('test8@gmail.com')
        cy.get('[name="date_funded1"]').type('03-03-2021')
        cy.get('[name="funded"]').clear().type('15240')
        cy.get('[name="max_participant_fund_per"]').type('100', { force: true })
        cy.get('#company_max_1').clear().type('3048')
        cy.get('#company_max_2').clear().type('7620')
        cy.get('#company_max_3').clear().type('4572')
        cy.get('[name="factor_rate"]').type('1.7')
        cy.get('[name="commission"]').type('18')
        cy.get('[name="pmnts"]').type('20')
        cy.get('[name="credit_score"]').type('500')
        // cy.get('[name="sub_status_flag"]').select('1', { force: true })
        cy.get('[name="sub_status_id"]').select('1', { force: true })
        cy.get('[name="advance_type"]').select('Weekly ACH', { force: true })
        cy.get('[name="marketplace_status"]').select('0', { force: true })
        cy.get('[name="source_id"]').select('1', { force: true })
        cy.get('[name="lender_id"]').select('LenderC', { force: true })
        // cy.get('[name="m_s_prepaid_status"]').check('2')
        // cy.get('[name="underwriting_fee"]').select('1.75', { force: true })
        // cy.get('[name="underwriting_status[]"]').check('1')
        // cy.get('[name="underwriting_status[]"]').check('2')
        cy.get('[name="ach_pull"]').check()
        cy.get('[name="account_holder_name"]').type('federal')
        cy.get('[name="routing_number"]').type('122235821')
        cy.get('[name="account_number"]').type('7770000033444')
        cy.get('#bankAcoountModalSubmit').click()
        cy.get('#merchant_create_form').submit();
        cy.get('.wrapper.demo > div.content-wrapper > section.content > div.col-md-12 > div > div.box-head > div > div > h4').invoke('text')
            .should('match', / Success/i)
    })
 // Set label field as `insurance1` for iocod9
    it('Creates merchant `iocod9`', () => {
        cy.get('[name="name"]').type('iocod9')
        cy.get('[name="first_name"]').type('merch9')
        cy.get('[name="state_id"]').select('12', { force: true })
        cy.get('[name="industry_id"]').select('8', { force: true })
        cy.get('[name="merchant_email"]').type('test9@gmail.com')
        cy.get('[name="date_funded1"]').type('02-05-2021')
        cy.get('[name="funded"]').clear().type('54253')
        cy.get('[name="max_participant_fund_per"]').type('100', { force: true })
        cy.get('#company_max_1').clear().type('27126.5')
        cy.get('#company_max_2').clear().type('27126.5')
        cy.get('[name="factor_rate"]').type('1.9')
        cy.get('[name="commission"]').type('5')
        cy.get('[name="pmnts"]').type('10')
        cy.get('[name="credit_score"]').type('500')
        // cy.get('[name="sub_status_flag"]').select('1', { force: true })
        cy.get('[name="sub_status_id"]').select('1', { force: true })
        cy.get('[name="advance_type"]').select('Daily ACH', { force: true })
        cy.get('[name="marketplace_status"]').select('0', { force: true })
        cy.get('[name="source_id"]').select('1', { force: true })
        cy.get('[name="lender_id"]').select('LenderD', { force: true })
        cy.get('[name="label"]').select('Insurance', {force: true})
        // cy.get('[name="m_s_prepaid_status"]').check('2')
        // cy.get('[name="underwriting_fee"]').select('1.75', { force: true })
        // cy.get('[name="underwriting_status[]"]').check('1')
        // cy.get('[name="underwriting_status[]"]').check('2')
        cy.get('[name="ach_pull"]').check()
        cy.get('[name="account_holder_name"]').type('federal')
        cy.get('[name="routing_number"]').type('082000549')
        cy.get('[name="account_number"]').type('00012345678')
        cy.get('#bankAcoountModalSubmit').click()
        cy.get('#merchant_create_form').submit();
        cy.get('.wrapper.demo > div.content-wrapper > section.content > div.col-md-12 > div > div.box-head > div > div > h4').invoke('text')
            .should('match', / Success/i)
    })


    // Set label field as `insurance1` for iocod10
    it('Creates merchant `iocod10`', () => {
        cy.get('[name="name"]').type('iocod10')
        cy.get('[name="first_name"]').type('merch10')
        cy.get('[name="state_id"]').select('11', { force: true })
        cy.get('[name="industry_id"]').select('8', { force: true })
        cy.get('[name="merchant_email"]').type('test10@gmail.com')
        cy.get('[name="date_funded1"]').type('03-14-2021')
        cy.get('[name="funded"]').clear().type('25000')
        cy.get('[name="max_participant_fund_per"]').type('75', { force: true })
        cy.get('#company_max_1').clear().type('5625')
        cy.get('#company_max_2').clear().type('6562.5')
        cy.get('#company_max_3').clear().type('6562.5')
        cy.get('[name="factor_rate"]').type('2')
        cy.get('[name="commission"]').type('8')
        cy.get('[name="pmnts"]').type('30')
        cy.get('[name="credit_score"]').type('500')
        // cy.get('[name="sub_status_flag"]').select('1', { force: true })
        cy.get('[name="sub_status_id"]').select('1', { force: true })
        cy.get('[name="advance_type"]').select('Weekly ACH', { force: true })
        cy.get('[name="marketplace_status"]').select('0', { force: true })
        cy.get('[name="source_id"]').select('1', { force: true })
        cy.get('[name="lender_id"]').select('LenderE', { force: true })
        cy.get('[name="label"]').select('Insurance', {force: true})
        // cy.get('[name="m_s_prepaid_status"]').check('2')
        // cy.get('[name="underwriting_fee"]').select('1.75', { force: true })
        // cy.get('[name="underwriting_status[]"]').check('1')
        // cy.get('[name="underwriting_status[]"]').check('2')
        cy.get('[name="ach_pull"]').check()
        cy.get('[name="account_holder_name"]').type('federal')
        cy.get('[name="routing_number"]').type('121122676')
        cy.get('[name="account_number"]').type('00012345678')
        cy.get('#bankAcoountModalSubmit').click()
        cy.get('#merchant_create_form').submit();
        cy.get('.wrapper.demo > div.content-wrapper > section.content > div.col-md-12 > div > div.box-head > div > div > h4').invoke('text')
            .should('match', / Success/i)
    })
})