<?php

namespace Tests\Feature\Http\Controllers\Admin;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Admin\DashboardController
 */
class DashboardControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin::dashboard::get-index'));

        $response->assertRedirect(to('/investor/dashboard'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function post_company_dashboard_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('admin::dashboard::company'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function post_dashboard_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('admin::dashboard::data-index'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function post_dashboard_transaction_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('admin::dashboard::dashboard-transaction'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function view_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin::dashboard::view', ['id' => $id]));

        $response->assertOk();
        $response->assertViewIs('admin.dashboard.details');
        $response->assertViewHas('paid_syndication_fee');
        $response->assertViewHas('page_title');
        $response->assertViewHas('tableBuilder');
        $response->assertViewHas('merchant');
        $response->assertViewHas('total_mgmnt_paid');
        $response->assertViewHas('paid_to_participant');
        $response->assertViewHas('ctd_sum');
        $response->assertViewHas('chart_data');
        $response->assertViewHas('balance');
        $response->assertViewHas('investment');

        // TODO: perform additional assertions
    }

    // test cases...
}
