<?php

namespace Tests\Feature\Http\Controllers\Admin;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Admin\MessageController
 */
class MessageControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin::messages::lists'));

        $response->assertOk();
        $response->assertViewIs('admin.messages');
        $response->assertViewHas('tableBuilder');
        $response->assertViewHas('page_title');
        $response->assertViewHas('investors');
        $response->assertViewHas('page_description');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function send_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('admin::messages::send'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function send_sample_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin::messages::sample'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
