<?php

namespace Tests\Feature\Http\Controllers\Admin;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Admin\ReconcileController
 */
class ReconcileControllerTest extends TestCase
{
    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin::reconcile-create'));

        $response->assertOk();
        $response->assertViewIs('admin.reconcile.create');
        $response->assertViewHas('lenders');
        $response->assertViewHas('page_title');
        $response->assertViewHas('action');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function delete_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('admin::reports::delete', ['id' => $id]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function lcreate_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin::get-reconcile_create', ['id' => $id]));

        $response->assertOk();
        $response->assertViewIs('admin.reconcile.lcreate');
        $response->assertViewHas('days');
        $response->assertViewHas('lender');
        $response->assertViewHas('amount');
        $response->assertViewHas('exising_days');
        $response->assertViewHas('title');
        $response->assertViewHas('vp_amount');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('admin::reconcile_store', ['id' => $id]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(to('admin/reconcile/create'));

        // TODO: perform additional assertions
    }

    // test cases...
}
