<?php

namespace Tests\Feature\Http\Controllers\Admin;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Admin\TemplateController
 */
class TemplateControllerTest extends TestCase
{
    /**
     * @test
     */
    public function assign_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('admin::template::assign'), [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertViewIs('admin.template.manage');
        $response->assertViewHas('page_title');
        $response->assertViewHas('template_types');
        $response->assertViewHas('template');
        $response->assertViewHas('action');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin::template::create'));

        $response->assertOk();
        $response->assertViewIs('admin.template.create');
        $response->assertViewHas('page_title');
        $response->assertViewHas('action');
        $response->assertViewHas('template_types');
        $response->assertViewHas('template_codes');
        $response->assertViewHas('template_models');
        $response->assertViewHas('enable');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function delete_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('admin::template::delete', ['id' => $id]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(withErrors('Cannot Delete Template!'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin::template::edit', ['id' => $id]));

        $response->assertOk();
        $response->assertViewIs('admin.template.create');
        $response->assertViewHas('page_title');
        $response->assertViewHas('template');
        $response->assertViewHas('action');
        $response->assertViewHas('template_types');
        $response->assertViewHas('template_codes');
        $response->assertViewHas('template_models');
        $response->assertViewHas('enable');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_theme_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin::template::'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin::template::index'));

        $response->assertOk();
        $response->assertViewIs('admin.template.index');
        $response->assertViewHas('page_title');
        $response->assertViewHas('tableBuilder');
        $response->assertViewHas('template_codes');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function manage_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin::template::manage', ['id' => $id, 'type' => $type]));

        $response->assertOk();
        $response->assertViewIs('admin.template.manage');
        $response->assertViewHas('page_title');
        $response->assertViewHas('template');
        $response->assertViewHas('template_types');
        $response->assertViewHas('action');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function remove_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('admin::template::remove'), [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertViewIs('admin.template.manage');
        $response->assertViewHas('page_title');
        $response->assertViewHas('template_types');
        $response->assertViewHas('template');
        $response->assertViewHas('action');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function row_data_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin::template::data'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function select_template_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('admin::template::selectTemplate'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function select_type_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('admin::template::selectType'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('admin::template::storeCreate'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('admin::template::update', ['id' => $id]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    // test cases...
}
