<?php

namespace Tests\Feature\Http\Controllers\Admin;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Admin\UserActivityLogController
 */
class UserActivityLogControllerTest extends TestCase
{
    /**
     * @test
     */
    public function get_index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin::activity-log.get.index'));

        $response->assertOk();
        $response->assertViewIs('admin.user_activity_log');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_investor_transaction_log_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin::'));

        $response->assertOk();
        $response->assertViewIs('admin.investor_transaction_log');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_records_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('api/admin/activity-log/records');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
