describe('DashBoard Test', () => {
    before(() => {
        cy.log_in()
        cy.visit('/admin/dashboard')
    })
    it('Checking Dashboard and items', () => {
        cy.get('[name="company[]"]').check()
        cy.get('#date_filter').click()
        cy.contains('Total RTR').should('be.visible')
        cy.contains('Expected RTR').should('be.visible')
        cy.get('body > div.wrapper.demo > div.content-wrapper > section.content > div.box.box-primary.sub_adm.box-sm-wrap > div > div.container-fluid > div > div:nth-child(3) > div > div.inner > p').contains('Investors').should('be.visible')
        cy.contains('Merchants').should('be.visible')
        cy.get('body > div.wrapper.demo > div.content-wrapper > section.content > div.box.box-primary.sub_adm.box-sm-wrap > div > div.container-fluid > div > div:nth-child(5) > div > div.inner > p').contains('Liquidity').should('be.visible')
        // cy.contains('VP Advance Funding').should('be.visible')
        // cy.get('body > div.wrapper.demo > div.content-wrapper > section.content > div.box.box-primary.sub_adm.box-sm-wrap > div > div.container-fluid > div > div.dashboard-companies > div:nth-child(3) > div').contains('Velocity').should('be.visible')
        // cy.contains('Liquidity').should('be.visible')
        cy.contains('Total Amount Invested').should('be.visible')
        cy.contains('Current Invested').should('be.visible')
        cy.contains('Blended Rate').should('be.visible')
        cy.contains('CTD').should('be.visible')
        cy.contains('Velocity Distribution').should('be.visible')
        cy.contains('Investor Distribution').should('be.visible')
        cy.contains('Pactolus Distribution').should('be.visible')
        cy.contains('Average Daily Balance').should('be.visible')
        cy.contains('Investor Portfolio').should('be.visible')
        cy.get('body > div.wrapper.demo > div.content-wrapper > section.content > div.box.box-primary.sub_adm.box-sm-wrap > div > div.container-fluid > div > div:nth-child(16) > div > div.inner > p').contains('Default Rate').should('be.visible')
        cy.contains('Over Payment').should('be.visible')
        cy.contains('Portfolio Value').should('be.visible')
        cy.contains('Pending To Velocity').should('be.visible')
        cy.contains('Pending To User Bank').should('be.visible')
        cy.url().should('include', '/admin/dashboard') 
        cy.url().should('eq', 'https://investorportal.test/admin/dashboard') 
    })
    it('Add Label and checking the URL', () => {
        cy.get('#label').select('1',{force:true})
        cy.get('#date_filter').click()
        cy.url().should('include', '/admin/dashboard') 
        cy.url().should('eq', 'https://investorportal.test/admin/dashboard') 
    })
    it('Add Type and checking the URL', () => {
        cy.get('#account_filter').select('Enabled Investors',{force:true})
        cy.get('#date_filter').click()
        cy.url().should('include', '/admin/dashboard') 
        cy.url().should('eq', 'https://investorportal.test/admin/dashboard') 
    })
})