describe('Transactions Test', () => {
    beforeEach(() => {
        cy.log_in()
        cy.visit('/admin/dashboard')
        cy.get('#cy_transactions').contains('Transactions').should('be.visible').click()
    })
    it('Checking Transaction Report page is visible', () => {
        cy.get('[data-cy="cy_transaction"]').contains('Transactions').should('be.visible').click({force:true})
        cy.url().should('include', '/admin/investors/transaction-report') 
        cy.url().should('include', Cypress.config().baseUrl + '/admin/investors/transaction-report')
            cy.get('#apply').should('be.visible').click({force:true})
            cy.url().should('include', Cypress.config().baseUrl + '/admin/investors/transaction-report')
            cy.get('#form_filter').contains('Download report')
            cy.get('#form_filter').should('be.visible')
            cy.url().should('include', Cypress.config().baseUrl + '/admin/investors/transaction-report')
            cy.get('#delete_multi_transaction').should('be.visible').click({force:true})
            cy.url().should('include', Cypress.config().baseUrl + '/admin/investors/transaction-report')
    })
    it('Checking Add Transaction page is visible', () => {
        cy.get('[data-cy="cy_addtransaction"]').contains('Add Transactions').should('be.visible').click({force:true})
        cy.url().should('include', '/admin/merchants/investor-transactions') 
        cy.url().should('include', Cypress.config().baseUrl + '/admin/merchants/investor-transactions')
            cy.contains('Reset').should('be.visible').click({force:true})
            cy.url().should('include', Cypress.config().baseUrl + '/admin/merchants/investor-transactions')
            cy.get('[value="View Investors"]').contains('View Investors')
            cy.get('[value="View Investors"]').should('be.visible').click()
            cy.url().should('include', Cypress.config().baseUrl + '/admin/merchants/investor-transactions')
            cy.get('#split_amount2').should('be.visible').check({force:true})
            cy.url().should('include', Cypress.config().baseUrl + '/admin/merchants/investor-transactions')
    })   
})