describe('Logs', () => {    
    beforeEach(() => { 
        cy.login({ email:'1email.33433@iocod.com'})
        cy.visit('/admin/dashboard')
        cy.get('#cy_logs').contains('Logs').should('be.visible').click({force:true})
    })
    it('Liquidity Log', ()=>{
        cy.get('#cy_liquity_log').contains('Liquidity Log').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/reports/liquidityLog')
        cy.get('#date_start1').click( {force:true})
        cy.get('#date_end1').click( {force:true})
        cy.get('#merchant_id').should('be.visible',{force:true})
        cy.get('#owner').should('be.visible',{force:true})
        cy.get('#investor').should('be.visible',{force:true})
        cy.get('#accountType').should('be.visible',{force:true})
        cy.get('#label').should('be.visible',{force:true})
        cy.get('#description').should('be.visible',{force:true})
        cy.get('#groupbypay').check({force:true})
        cy.get('[value="Apply Filter"]').should('be.visible', {force:true}).click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/reports/liquidityLog')
        cy.get('[value="Download"]').should('be.visible', {force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/reports/liquidityLog')
    })
    it('Merchant Liquidity Log', ()=>{
        cy.get('#cy_mer_liq_log').contains('Merchant Liquidity Log').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/reports/MerchantliquidityLog')
        cy.get('#date_start1').click( {force:true})
        cy.get('#date_end1').click( {force:true})
        cy.get('#merchant_id').should('be.visible',{force:true})
        cy.get('#owner').should('be.visible',{force:true})
        cy.get('#investor').should('be.visible',{force:true})
        cy.get('#groupbypay').check({force:true})
        cy.get('#accountType').should('be.visible',{force:true})
        cy.get('#description').should('be.visible',{force:true})
        cy.get('[value="Apply Filter"]').should('be.visible', {force:true}).click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/reports/MerchantliquidityLog')
    })

    it('Merchant Status Log', ()=>{
        cy.get('[data-cy="cy_mer_status_logs"]').contains('Merchant Status Log').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/merchant_status_log')
        cy.get('#date_start1').click( {force:true})
        cy.get('#date_end1').click( {force:true})
        cy.get('#status_id').should('be.visible',{force:true})
        cy.get('#merchants').should('be.visible',{force:true})
        cy.get('[value="Apply Filter"]').should('be.visible', {force:true}).click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/merchant_status_log')
    })
    it('User Activity Log', ()=>{
        cy.get('[data-cy="cy_user_activity_logs"]').contains('User Activity Log').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/activity-log')
        cy.get('[name="from_date1"]').click( {force:true})
        cy.get('[name="to_date1"]').click( {force:true})
        cy.get('[name="search_type"]').should('be.visible',{force:true})
        cy.get('[name="search_user"]').should('be.visible',{force:true})
        cy.get('[name="search_action_user"]').should('be.visible',{force:true})
        cy.get('[name="search_action"]').should('be.visible',{force:true})
        cy.get('#apply_filter').contains('Apply Filter').should('be.visible', {force:true}).click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/activity-log')
    })
    it('Investor Transaction Log', ()=>{
        cy.get('[data-cy="cy_investor_trans_logs"]').contains('Investor Transaction Log').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/investor-transaction-log')
        cy.get('#from-date').click( {force:true})
        cy.get('#to-date').click( {force:true})
        cy.get('[name="search_user"]').should('be.visible',{force:true})
        cy.get('[name="search_action"]').should('be.visible',{force:true})
        cy.get('[name="search_object_id"]').should('be.visible',{force:true})
        cy.get('#apply_filter').contains('Apply Filter').should('be.visible', {force:true}).click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/investor-transaction-log')
    })
    it('Messages Log', ()=>{
        cy.get('[data-cy="cy_message_logs"]').contains('Messages Log').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/messages')
        cy.get('#from_date1').click( {force:true})
        cy.get('#to_date1').click( {force:true})
        cy.get('#status').should('be.visible',{force:true})
        cy.get('#getButton').contains('Apply').should('be.visible',{force:true}).click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/messages')
    })
    it('Messages Log', ()=>{
        cy.get('[data-cy="cy_mail_logs"]').contains('Mail Log').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/merchants/mail-log')
        cy.get('#date_from1').click( {force:true})
        cy.get('#date_to1').click( {force:true})
        cy.get('#merchants').should('be.visible',{force:true})
        cy.get('#mail_type').should('be.visible',{force:true})
        cy.get('#date_filter').get('[value="Apply Filter"]').should('be.visible',{force:true}).click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/merchants/mail-log')
        cy.get('[value="Download"]').should('be.visible',{force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/merchants/mail-log')
    })
})
