describe('Settings', () => {    
    beforeEach(() => { 
        cy.viewport(2000, 1700)
        cy.login({ email:'1email.33433@iocod.com'})
        cy.visit('/admin/dashboard')
        cy.get('#cy_settings').contains('Settings').should('be.visible').click({force:true})
    })
    it('Advance Settings', ()=>{
        cy.get('#cy_advanced_settings').contains('Advance Settings').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/settings')
        cy.get('#email').should('be.visible', {force:true})
        cy.get('#inputRate').should('be.visible', {force:true})
        cy.get('#default_payment').should('be.visible', {force:true})
        cy.get('#date_start1').click({force:true})
        cy.get('[value="Update"]').should('be.visible', {force:true})
    })
    it('System Settings', ()=>{
        cy.get('[data-cy="system_settings"]').contains('System Settings').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/settings/system_settings')
        cy.get('#sub_status').should('be.visible', {force:true})
        cy.get('[value="Update"]').should('be.visible', {force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/settings/system_settings')
    })
    it('Re Assign', ()=>{
        cy.get('[data-cy="Re-assign"]').contains('Re-assign').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/re-assign')
        cy.get('#investor_id').should('be.visible', {force:true})  
        cy.get('#clear_all').contains('Clear All').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/re-assign#')
        cy.get('[value="Transfer"]').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/re-assign')
        cy.get('[value="Assign to all other investors"]').should('be.visible', {force:true}).click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/re-assign?investor_id=Select+An+Investor+To+Withdraw+Money.')
    })
    it('All Status', ()=>{
        cy.get('[data-cy="all_status"]').contains('All Status').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/sub_status')
        cy.contains('Add Status').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/sub_status/create')
        cy.get('[value="Create"]').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/sub_status/create')
        cy.contains(' View all ').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/sub_status')
        cy.get('#status > tbody > tr:nth-child(1) > td:nth-child(3) > a').contains('Edit').should('be.visible').first().click({force:true})
        cy.url().should('include', Cypress.config().baseUrl + '/admin/sub_status/edit/')
        cy.contains('View al').should('have.attr', 'href', 'https://investorportal.test/admin/sub_status').should('be.visible')
        cy.get('[value="Update"]').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/sub_status')
        cy.get('[value="Delete"]').should('be.visible').first().click({force:true})
        cy.on('window:confirm', () => false)
    })
    it('Label', ()=>{
        cy.get('[data-cy="label"]').contains('Label').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/label')
        cy.contains('Add Status').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/label/create')
        cy.get('[value="Create"]').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/label/create')
        cy.contains(' View all ').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/label')
        cy.get('#status > tbody > tr:nth-child(1) > td:nth-child(3) > a').contains('Edit').should('be.visible').first().click({force:true})
        cy.url().should('include', Cypress.config().baseUrl + '/admin/label/edit/')
        cy.contains('View al').should('have.attr', 'href', 'https://investorportal.test/admin/label').should('be.visible')
        cy.get('[value="Update"]').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/label')
        cy.get('[value="Delete"]').should('be.visible').first().click({force:true})
        cy.on('window:confirm', () => false)
    })
    it('Sub Status Flag', ()=>{
        cy.get('[data-cy="sub_status_flag"]').contains('Sub Status Flag').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/sub_status_flag')
        cy.contains('Add Sub Status Flag').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/sub_status_flag/create')
        cy.get('[value="Create"]').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/sub_status_flag/create')
        cy.contains(' View all ').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/sub_status_flag')
        cy.get('#status > tbody > tr:nth-child(1) > td:nth-child(3) > a').contains('Edit').should('be.visible').first().click({force:true})
        cy.url().should('include', Cypress.config().baseUrl + '/admin/sub_status_flag/edit/')
        cy.contains('View al').should('have.attr', 'href', 'https://investorportal.test/admin/sub_status_flag').should('be.visible')
        cy.get('[value="Update"]').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/sub_status_flag')
        cy.get('[value="Delete"]').should('be.visible').first().click({force:true})
        cy.on('window:confirm', () => false)
    })
    it('Calander', ()=>{
        cy.get('[data-cy="calander_for_holidays"]').contains('Calender for Holidays').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/fullcalender')
    })
    it('Liquidity Adjuster', ()=>{
        cy.get('[data-cy="liq_adjuster"]').contains('Liquidity Adjuster').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/two-factor-authentication')
        cy.contains('Edit').should('be.visible').first().click({force:true})
        cy.url().should('include', Cypress.config().baseUrl + '/admin/admin/create_liquidity_adjuster/')
        cy.get('[value="Update"]').should('be.visible').click({force:true})
        cy.url().should('include', Cypress.config().baseUrl + '/admin/admin/create_liquidity_adjuster/')
        cy.contains('View List').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/admin/liquidity_adjuster')
    })
    it('Two Factor Authentication', ()=>{
        cy.get('[data-cy="two_factor_auth"]').contains('Two Factor Authentication').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/two-factor-authentication')
        cy.contains('Enable').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/enable-two-factor-auth')
        cy.contains('Connect Phone').should('be.visible').click({force:true})
        cy.url().should('eq', Cypress.config().baseUrl + '/admin/enable-two-factor-auth')

    })
  
})